[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
resolution = false
skip-lint = false

[programs.localnet]
oft = "G2BYTnfGCMQAErMZkTBCFSapKevzf6QCjizjXi8hFEtJ"
transfer_hook = "Hook111111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./junk-id.json"

[scripts]
test = "npx jest test/anchor"
