#   .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-  .-.-.   .-.-.   .-.-
#  / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \ / / \ \ / / \ \ / / \
# `-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'   `-'   `-`-'   `-`-'
#
#             Workflow that checks the code commited to the main branch
#                           and publishes the packages
#
#   .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-  .-.-.   .-.-.   .-.-
#  / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \ / / \ \ / / \ \ / / \
# `-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'   `-'   `-`-'   `-`-'
# `.github/workflows/update-lockfiles.yaml` references this workflow name, make sure
# to update the reference if you change the name.
name: Check & publish

on:
  push:
    branches:
      - main

# We only want one workflow to run at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  check:
    name: Check code
    uses: ./.github/workflows/reusable-test.yaml
    secrets: inherit

  publish:
    name: Publish NPM packages
    needs: check
    uses: ./.github/workflows/reusable-publish.yaml
    secrets: inherit
